import type { AtlasDef } from "../atlasDefs";
import { BuildingSprites } from "./buildings";

export const lasrWswardsAtlas: AtlasDef = {
        compress: false,
     images: [
         "map/lasr_Swrds_Crate.svg",
         "map/lasr_swrds_bush.svg",
         "map/map-tree-02-lasr-swards.svg",
         "map/map-tree-01-lasr-swards.svg",
         "map/map-tree-03-lasr-swards.svg",
         "map/space-crate.svg",
         "map/map-building-greenhouse-ceiling-01.svg",
         "map/map-building-greenhouse-floor-01.svg",
         "map/map-bunker-chrys-chamber-ceiling-01.svg",
         "map/map-bunker-chrys-chamber-floor-01a.svg",
         "map/map-bunker-chrys-chamber-floor-01b.svg",
         "map/map-bunker-chrys-compartment-ceiling-01a.svg",
         "map/map-bunker-chrys-compartment-ceiling-01b.svg",
         "map/map-bunker-chrys-compartment-ceiling-02a.svg",
         "map/map-bunker-chrys-compartment-ceiling-02b.svg",
         "map/map-bunker-chrys-compartment-ceiling-03a.svg",
         "map/map-bunker-chrys-compartment-ceiling-03b.svg",
         "map/map-bunker-chrys-compartment-floor-01a.svg",
         "map/map-bunker-chrys-compartment-floor-01b.svg",
         "map/map-bunker-chrys-compartment-floor-02a.svg",
         "map/map-bunker-chrys-compartment-floor-02b.svg",
         "map/map-bunker-chrys-compartment-floor-03a.svg",
         "map/map-bunker-crossing-ceiling-01.svg", 
         "map/map-bunker-crossing-chamber-ceiling-01.svg",
         "map/map-bunker-crossing-chamber-floor-01a.svg",
         "map/map-bunker-crossing-chamber-floor-01b.svg",
         "map/map-bunker-crossing-chamber-floor-01c.svg",
         "map/map-bunker-crossing-chamber-floor-02.svg",
         "map/map-bunker-crossing-chamber-floor-03.svg",
         "map/map-bunker-crossing-compartment-ceiling-01a.svg",
         "map/map-bunker-crossing-compartment-ceiling-01b.svg",
         "map/map-bunker-crossing-compartment-floor-01.svg",
         "map/map-bunker-crossing-compartment-floor-02.svg",
         "map/map-bunker-crossing-floor-01.svg",
         "map/map-bunker-generic-ceiling-02.svg",
         "map/map-bunker-generic-floor-03.svg",
         "map/map-bunker-hydra-ceiling-01.svg",
         "map/map-bunker-hydra-chamber-ceiling-01.svg",
         "map/map-bunker-hydra-chamber-ceiling-02.svg",
         "map/map-bunker-hydra-chamber-ceiling-03.svg",
         "map/map-bunker-hydra-chamber-floor-01a.svg",
         "map/map-bunker-hydra-chamber-floor-01b.svg",
         "map/map-bunker-hydra-chamber-floor-02.svg",
         "map/map-bunker-hydra-chamber-floor-03.svg",
         "map/map-bunker-hydra-compartment-ceiling-01.svg",
         "map/map-bunker-hydra-compartment-ceiling-02.svg",
         "map/map-bunker-hydra-compartment-ceiling-03.svg",
         "map/map-bunker-hydra-compartment-floor-01.svg",
         "map/map-bunker-hydra-compartment-floor-02.svg",
         "map/map-bunker-hydra-compartment-floor-03.svg",
         "map/map-bunker-hydra-floor-01.svg",
         "map/map-bunker-hydra-floor-04.svg",
         "map/map-complex-warehouse-floor-01.svg",
         "map/map-complex-warehouse-floor-02.svg",
         "map/map-complex-warehouse-floor-03.svg",
         "map/map-planter-01.svg",
         "map/map-planter-02.svg",
         "map/map-planter-03.svg",
         "map/map-planter-04.svg",
         "map/map-planter-05.svg",
         "map/map-planter-res-01.svg",
        "loot/loot-perk-leprechaun.svg",
        "loot/loot-melee-lasr-sword-01.svg",
        "loot/loot-melee-lasr-sword-02.svg",
        "loot/loot-melee-lasr-sword-03.svg",
        "loot/loot-lasr-sword-01.svg",
        "loot/loot-lasr-sword-02.svg",
        "loot/loot-lasr-sword-03.svg",

    ],
};
